plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

remote_theme: ucsb-cs-course-repos/course-repo-jekyll-theme
url: https://ucsb-cs24-f24.github.io/cs24-f24
baseurl: "/cs24-f24"
name: "CS24 Fall 2024"
course: "CS24"
title: "UCSB CS24 F24"
github_url: https://github.com/ucsb-cs24-f24/cs24-f24
quarter: "Fall 2024"
class_org:
   name: ucsb-cs24-f24
   url: https://github.com/ucsb-cs24-f24
   githublinker: CS24 F24

kramdown:
   parse_block_html: true

exclude:
   - vendor
include:
  - _pages

timezone: America/Los_Angeles

collections:
  lab:
    output: true
    permalink: /lab/:path/
    last_before: false
  pa:
    output: true
    permalink: /pa/:path/
    last_before: false
  exam:
    output: true
    permalink: /exam/:path/
  lectures:
    output: true
    permalink: /lectures/:path/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: default
  -
    scope:
      path: ""
      type: lab
    values:
      layout: lab
  -
    scope:
      path: ""
      type: pa
    values:
      layout: lab
  -
    scope:
      path: ""
      type: exam
    values:
      layout: exam_info
  -
    scope:
      path: ""
      type: info
    values:
      layout: default
  -
    scope:
      path: ""
      type: lectures
    values:
      layout: lecture

theme: jekyll-theme-cayman
