plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

remote_theme: ucsb-cs-course-repos/course-repo-jekyll-theme
#remote_theme: pmarsceill/just-the-docs@v0.3.3
url: https://ucsb-cs24.github.io/w24 
baseurl: "/w24"  
instructor: "Diba Mirza"
name: "CS24 Winter 2024"
course: "CS24"
course_title: "Problem Solving with Computers II"
title: "UCSB CS24 W24"
github_url: https://github.com/ucsb-cs24/w24
qtr: "W24"
quarter: "Winter 2024"
lecture_times: "MW 11:00a - 12:15p"
lecture_location: "TD-W 1701"
lab_times: "R: 2p, 3p, 4p, 5p, and 6p"
tas: "Joseph Ng, Nawel Alioua, Shinda Huang, Xinlei Feng, Yaoyi Bai"
ulas: "Zack Glazewski, Ally Chu, Sanjana Shankar"
class_org:
   name: ucsb-cs24-w24
   url: https://github.com/ucsb-cs24-w24
   githublinker: CS24 W24
   
lect_repo: https://github.com/ucsb-cs24-w24/cs24-w24-lectures
start_week: 1
start_date: 2024-01-07
num_weeks: 10
extra_exam_week: true

instructor_url: https://ucsb-cs24.github.io/instructor

cal_dates: >
  [
  {"label":"First day of classes", "date":"2024-01-08" },
  {"label":"Drop deadline (no W grade)","date":"2023-10-25" },
  {"label":"Thanksgiving - No lecture", "date":"2023-11-22" },
  {"label":"F23 Instruction Ends", "date":"2023-12-08" },  
  {"label":"F23 Quarter Ends", "date":"2023-12-15" }          
  ]

kramdown:
   parse_block_html: true

exclude:
   - vendor
include:
  - _pages

timezone: America/Los_Angeles

collections:
  lab:
    output: true
    permalink: /lab/:path/
    last_before: false
  pa:
    output: true
    permalink: /pa/:path/
    last_before: false
  exam:
    output: true
    permalink: /exam/:path/
  info:
    output: true
    permalink: /info/:path/
  lectures:
    output: true
    permalink: /lectures/:path/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: default
  -
    scope:
      path: ""
      type: hwk
    values:
      layout: hwk
  -
    scope:
      path: ""
      type: lab
    values:
      layout: lab
  -
    scope:
      path: ""
      type: pa
    values:
      layout: lab
  -
    scope:
      path: ""
      type: exam
    values:
      layout: exam_info
  -
    scope:
      path: ""
      type: info
    values:
      layout: default
  -
    scope:
      path: ""
      type: lectures
    values:
      layout: lecture
  -
    scope:
      path: "syllabus.md"
      type: info
    values:
      layout: handout

theme: jekyll-theme-cayman
